[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "diffswe2d"
version = "0.1.0"
description = "DiffSWE2d: A differentiable Shallow Water Equations solver"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "torch>=2.1",
    "netCDF4>=1.6",
    "numpy>=1.24",
    "xarray>=2024.1",
    "scipy>=1.10",
    "pytest>=7"
]

[tool.setuptools]
packages = ["diffswe2d"]

[tool.setuptools.package-dir]
diffswe2d = "src"